"""
Django settings for ecom_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
import os


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'products',
    'orders',  # Your products app
    'corsheaders',  # If you are using CORS
    'django_filters',  # If you are using Django filters    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL  = "/media/"

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

PHONENUMBER_DEFAULT_REGION = "DZ"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py

JAZZMIN_SETTINGS = {
    # Site Branding
    "site_title": "My Store Dashboard",
    "site_header": "🛒 Store Admin",
    "site_logo": "<your-logo-path-here>.png",
    "welcome_sign": "Welcome, Store Owner!",

    # Navbar (top)
    "show_navbar": True,
    "user_display": True,

    # Sidebar (left)
    "show_sidebar": True,
    "sidebar_nav_collapsed": False,

    # Color/theme
    "topnavbar_dark": False,
    "dark_mode_theme": "black",
    "theme": "flatly",

    # Custom order of apps/models
    "ordering": ["orders", "products", "auth"],

    # Model icons
    "icons": {
        "orders.Order": "fas fa-receipt",
        "orders.OrderItem": "fas fa-box-open",
        "products.Product": "fas fa-tag",
        "products.ProductVariant": "fas fa-barcode",
    },

    # Custom menu links under the “orders” app
    "custom_links": {
        "orders": [
            {
                "name": "Pending Orders",
                "url": "/admin/orders/order/?order_status__exact=Pending",
                "icon": "fas fa-hourglass-half",
                "permissions": ["orders.view_order"],
            },
            {
                "name": "Accepted Orders",
                "url": "/admin/orders/order/?order_status__exact=Accepted",
                "icon": "fas fa-check-circle",
                "permissions": ["orders.view_order"],
            },
            {
                "name": "Rejected Orders",
                "url": "/admin/orders/order/?order_status__exact=Rejected",
                "icon": "fas fa-times-circle",
                "permissions": ["orders.view_order"],
            },
        ],
    },

    # Dashboard Cards
    "welcome_cards": [
        {
            "name": "Total Orders",
            "type": "html",
            "content": """
                <div class="card text-center">
                    <div class="card-body">
                      <h5 class="card-title">Orders Today</h5>
                      <p class="card-text">{{ orders_today_count }}</p>
                    </div>
                </div>
            """,
        },
    ],

    # Hide or show apps/models
    "hide_models": [
        "auth.Group",
    ],
}
