# Generated by Django 4.2.7 on 2025-06-27 14:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='commune',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='costumer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='DZ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
