# Generated by Django 4.2.7 on 2025-06-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_wilaya_order_commune_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='costumer_adress',
        ),
    ]
