# Generated by Django 4.2.7 on 2025-06-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_costumer_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('A Domicile', 'A Domicile'), ('Bureau', 'Bureau')], default='Bureau', max_length=50),
        ),
    ]
