# Generated by Django 4.2.7 on 2025-06-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.commune'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.wilaya'),
        ),
    ]
