# Generated by Django 4.2.7 on 2025-06-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_commune_alter_order_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wilaya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.wilaya'),
            preserve_default=False,
        ),
    ]
