# Generated by Django 4.2.7 on 2025-06-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
    ]
