# Generated by Django 4.2.7 on 2025-06-02 15:52

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_to),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_to_variant),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
