# Generated by Django 4.2.7 on 2025-06-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_name_alter_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
