# Generated by Django 4.2.7 on 2025-06-16 15:19

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_to),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_to_variant),
        ),
    ]
